language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

dist: trusty

install:
    - pip install -U pip
    - python setup.py install

script:
    - exit 0

notifications:
    email:
        on_success: change
        on_failure: change
