language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

dist: trusty

install:
    - pip install poetry
    - poetry install

script:
    - poetry run pyeupi -h
    - portry run mypy .

notifications:
    email:
        on_success: change
        on_failure: change
